### PR TITLE
Chapter 2 Python Solutions

### PR DESCRIPTION
**Pull request by kv-kunalvyas**

### CODE REVIEW

**Comment by mmermerkaya** [comment]
Hi, I committed solutions for all chapter 2 problems already, maybe we could merge our solutions somehow?

https://github.com/mmermerkaya/CtCI-6th-Edition/commit/f7e242006a81dc3a2c410b94d0efa64472714365

**Comment by kv-kunalvyas** [comment]
Sure, I will close my pull request for the time being and will create it again when yours is merged. However, can you please add the python files for chapter 2 inside another problem folder like in chapter 1? `Python/Chapter 2/6_Palindrome.py` should be `Python/Chapter 2/6_Palindrome/6_Palindrome.py` and so on. This will look a lot cleaner. Thanks.

**Comment by mmermerkaya** [comment]
Sorry, I completely forgot about this until my PR got merged today. I didn't put them in different folders because it's much simpler to import LinkedList.py from the solution files this way. And I don't really think we need a folder for a single file. If we had more than one file for some solutions, then it would make more sense to separate them into folders.

**Comment by kv-kunalvyas** [comment]
Yes, you are correct, but considering alternate solutions with different approaches/complexities by others, it makes sense to have multiple files in that question's folder. Moreover, I got this intuition from the 5th edition's github repo. Check [this](https://github.com/careercup/ctci/tree/master/python/Chapter%201/Question1_1) for example.

**Pull request closed without merging**
